#!/bin/bash

set -e

lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free non-free-firmware" \
  --bootappend-live "boot=live components quiet splash" \
  --linux-flavours amd64 \
  --mirror-bootstrap https://deb.debian.org/debian/ \
  --mirror-binary https://deb.debian.org/debian/ \
  --mirror-chroot-security https://security.debian.org/debian-security/ \
  --apt-recommends true
